/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MKE02Z16xxx4
package_id: MKE02Z16VFM4
mcu_data: ksdk2_0
processor_version: 7.0.1
pin_labels:
- {pin_num: '16', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6, label: SO2}
- {pin_num: '15', pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7, label: SO2_REF}
- {pin_num: '14', pin_signal: PTC0/FTM2_CH0/ADC0_SE8, label: CO}
- {pin_num: '13', pin_signal: PTC1/FTM2_CH1/ADC0_SE9, label: CO_REF}
- {pin_num: '12', pin_signal: PTC2/FTM2_CH2/ADC0_SE10, label: O3}
- {pin_num: '11', pin_signal: PTC3/FTM2_CH3/ADC0_SE11, label: O3_REF}
- {pin_num: '20', pin_signal: PTA6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2, label: NO2}
- {pin_num: '19', pin_signal: PTA7/FTM2_FLT2/ACMP1_IN1/ADC0_SE3, label: NO2_REF}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '28', peripheral: UART1, signal: RX, pin_signal: PTC6/UART1_RX}
  - {pin_num: '27', peripheral: UART1, signal: TX, pin_signal: PTC7/UART1_TX}
  - {pin_num: '16', peripheral: ADC, signal: 'SE, 6', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6}
  - {pin_num: '15', peripheral: ADC, signal: 'SE, 7', pin_signal: PTB3/KBI0_P7/SPI0_MOSI/FTM0_CH1/ADC0_SE7}
  - {pin_num: '14', peripheral: ADC, signal: 'SE, 8', pin_signal: PTC0/FTM2_CH0/ADC0_SE8}
  - {pin_num: '13', peripheral: ADC, signal: 'SE, 9', pin_signal: PTC1/FTM2_CH1/ADC0_SE9}
  - {pin_num: '12', peripheral: ADC, signal: 'SE, 10', pin_signal: PTC2/FTM2_CH2/ADC0_SE10}
  - {pin_num: '11', peripheral: ADC, signal: 'SE, 11', pin_signal: PTC3/FTM2_CH3/ADC0_SE11}
  - {pin_num: '20', peripheral: ADC, signal: 'SE, 2', pin_signal: PTA6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2}
  - {pin_num: '19', peripheral: ADC, signal: 'SE, 3', pin_signal: PTA7/FTM2_FLT2/ACMP1_IN1/ADC0_SE3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
